import React from 'react';
import './Resources.css';
import { Databases } from '../Links';
import Footer from '../Footer';
import { Assets } from '../Assets';

function DatabasesPage() {
    const fontSize = "17px"; // for some reason my css stopped working so I had to use inline styling

    return (
        <>
            <div class="page-container">
                <h1 class="section-title">Databases</h1>

                <div class="database-item">
                    <img src={Assets.images.oprlm_db} alt="Database" loading="lazy" class="database-img"/>
                    <div>
                        <a href={Databases.OPRLM}><h3>OPRLM (Orientations of Proteins in Realistic Lipid Membranes) </h3> </a>
                        <p class="database-text" style={{fontSize: fontSize}}>
                            The OPRLM database provides experimental 3D structures from the RCSB Protein Data bank 
                            (PDB) of transmembrane TM and peripheral membrane proteins and membrane-active 
                            peptides that are oriented in lipid membranes using the PPM method. OPM offers 
                            structural classification of proteins into families and superfamilies and 
                            various browsing, searching, sorting, and visualization options, such as 
                            displaying images simultaneously for all proteins from specific families, 
                            superfamilies, or membranes. It also provides protein topology, preferred 
                            intracellular localization, interactive visualization by Jmol, GLmol, LiteMol, 
                            and iCn3D, and links to related web resources. </p>
                    </div>
                </div>
                <div class="database-item">
                    <img src={Assets.images.MEMBRANOME} alt="Database" loading="lazy" class="database-img"/>
                    <div>
                        <a href={Databases.MEMBRANOME}><h3>MembranomeX</h3></a>
                        <p className="database-text" style={{fontSize: fontSize}}>
                            The MembranomeX database compiles available structural and functional information 
                            for the complete sets of single-pass transmembrane (i.e., bitopic) proteins from 
                            twenty organisms. The database provides protein classification, amino acid sequences, 
                            topologies, intracellular localizations, domain organization (from UniProt and InterPro), 
                            experimentally supported protein-protein interactions (from HINT and APID), 
                            list of known protein complexes (from Reactome, Complex Portal, CORUM, and PDB), 
                            associated pathways (from KEGG), mutagenesis data (from MutDB), and links to related 
                            bioinformatics resources. The database holds experimental (from PDB) and newly modeled 3D 
                            structures of full-length bitopic proteins and protein complexes generated by AlphaFold2 
                            and AlphaFold3, and models of transmembrane helical dimers generated by TMDOCK. Structures 
                            of full-length protein monomers from the AlphaFold Protein Structure Database were parsed and 
                            reassembled in membranes by our software. Protein models were positioned in the lipid bilayer by PPM. 
                            The database also provides tools for advanced search, protein network analysis, and structural 
                            visualization to facilitate comparative analysis of bitopic proteins. </p>
                    </div>
                </div>
                <div class="database-item">
                    <img src={Assets.images.permm_db} alt="Database" loading="lazy" class="database-img"/>
                    <div>
                        <a href={Databases.PERMM}><h3>PerMM (Permeabiity of Molecules across Membranes)</h3></a>
                        <p className="database-text" style={{fontSize: fontSize}} >
                            The PerMM database collects experimental and calculated permeability coefficients of 
                            drug-like molecules obtained for artificial and natural membranes, 
                            including BLM, PAMPA, Caco-2/MDCK cells, and BBB supplemented by 
                            references and other related data. It currently contains 507 molecules, 
                            ranging from small organic compounds to natural products of diverse 
                            chemical structures. The database provides downloadable coordinate 
                            files and interactive visualization to represent optimal localization 
                            and translocation pathways of molecules across the lipid bilayer. 
                            Presented data allow assessment of the contribution of the passive 
                            diffusion to transport of drugs and other small molecules across 
                            biological membranes. 
                        </p>
                    </div>
                </div>
            </div>
            <Footer />
        </>
    );
}
export default DatabasesPage;

